USE coches;
CREATE TABLE modelos(
id INT AUTO_INCREMENT,
nombre VARCHAR(25),
id_marca INT,
PRIMARY KEY (id),
FOREIGN KEY(id_marca) REFERENCES marcas(id)ON DELETE CASCADE ON UPDATE CASCADE
 )
 ENGINE=INNODB;